# Generated by Django 5.2.3 on 2025-06-30 14:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'xlsx', 'xls'])])),
                ('original_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.IntegerField()),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('data_source', models.CharField(choices=[('random', 'Random Data'), ('upload', 'Upload CSV'), ('local', 'Tumor Dataset')], max_length=20)),
                ('sample_size', models.IntegerField(blank=True, null=True)),
                ('selected_column', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(default='blue', max_length=20)),
                ('bins', models.IntegerField(default=30)),
                ('show_plot', models.BooleanField(default=True)),
                ('show_stats', models.BooleanField(default=True)),
                ('show_correlation', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analysis.uploadedfile')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
