# Generated by Django 5.2.3 on 2025-07-20 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysissession',
            name='svm_kernel',
            field=models.CharField(choices=[('linear', 'Linear'), ('poly', 'Polynomial'), ('rbf', 'RBF (Radial Basis Function)'), ('sigmoid', 'Sigmoid')], default='rbf', max_length=20),
        ),
        migrations.AddField(
            model_name='analysissession',
            name='svm_target_column',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='analysissession',
            name='svm_test_size',
            field=models.FloatField(default=0.2),
        ),
        migrations.CreateModel(
            name='SVMResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.FloatField()),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('f1_score', models.FloatField()),
                ('kernel_type', models.CharField(max_length=20)),
                ('test_size', models.FloatField()),
                ('target_column', models.CharField(max_length=100)),
                ('feature_columns', models.JSONField()),
                ('class_labels', models.JSONField()),
                ('confusion_matrix', models.JSONField()),
                ('n_samples', models.IntegerField()),
                ('n_features', models.IntegerField()),
                ('n_train', models.IntegerField()),
                ('n_test', models.IntegerField()),
                ('training_date', models.DateTimeField(auto_now_add=True)),
                ('analysis_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='svm_results', to='analysis.analysissession')),
            ],
            options={
                'ordering': ['-training_date'],
            },
        ),
    ]
